apiVersion: apps/v1
kind: Deployment
metadata:
  name: chilli
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chilli
  template:
    metadata:
      labels:
        app: chilli
    spec:
      containers:
      - image: okteto.dev/chilli:latest
        name: chilli
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "17024f18-1f54-42e9-927d-3ba95fbe57df"
        - name: Vless_Path
          value: "/dhterger814"
        - name: Vmess_UUID
          value: "17024f18-1f54-42e9-927d-3ba95fbe57df"
        - name: Vmess_Path
          value: "/fdtetdj815"
        - name: Share_Path
          value: "/v2link"
